title   : Блог персонального помічника
email   : passist@gmail.com
tel     : +38 050 256 21 25
telegram: '@passist'
description: >- # this means to ignore newlines until "baseurl:"
  Мій досвід включає досить тривалий
  період роботи в якості персональної помічниці.
  Я хочу розповісти вам про цю професію.
language: ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Pagination Settings
collections:
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
autopages:
  enabled: true
  tags: 
    layouts: 
      - tags.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  categories:
    layouts:
      - category.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  collections:
    layouts:
      - autopage_collection.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  posts:
    layouts: 
      - posts.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2
# Build settings
env: production
minify_html: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:year/:month/:day/:title:output_ext
excerpt_separator: <!--more-->
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/bundle/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - gulp.js
  - dist
