title   : Блог персонального ассистента
email   : rspersonal@gmail.com
tel     : 8 495 256 21 21
telegram: '@rspersonal'
description: >- # this means to ignore newlines until "baseurl:"
  Мой опыт включает в себя достаточно продолжительный 
  период работы персональным ассистентом. 
  Хочу рассказать вам об этой профессии.
language: ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Pagination Settings
collections:
 authors:
  output: true
  permalink: /author/:name/
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title:output_ext
#excerpt_separator: <!--more-->
autopages:
  enabled: true
  tags: 
    layouts: 
      - tags.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  categories:
    layouts:
      - category.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  collections:
    layouts:
      - autopage_collection.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
  posts:
    layouts: 
      - posts.html
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true
# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2
# Build settings
env: production
minify_html: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - octopress-minify-html
permalink: /:year/:month/:day/:title:output_ext
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/bundle/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
