title   : Блог персонального ассистента
email   : rspersonal@gmail.com
tel     : 8 495 256 21 21
telegram: '@rspersonal'
description: >- # this means to ignore newlines until "baseurl:"
  Мой опыт включает в себя достаточно продолжительный 
  период работы персональным ассистентом. 
  Хочу рассказать вам об этой профессии.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:year/:month/:day/:title:output_ext
exclude:
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
